- app/Http/Controllers/NotificationController.php
- app/Models/Notification.php
- database/migrations/2025_04_24_001843_create_notifications_table.php
- routes/api.php
-Set up database schema for notifications
-Create backend endpoints (send, retrieve, update notifications)
> Created a New Branch, Database Scehma and Endpoints

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/PasswordResetLinkController.php
- app/Models/User.php
- app/Notifications/CustomResetPassword.php
- public/images/arrow-left-admin.svg
- public/images/arrow-left.svg
- resources/css/app.css
- resources/views/auth/forgot-password.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/password-reset-confirmation.blade.php
- resources/views/auth/reset-password.blade.php
- resources/views/emails/custom-reset-password.blade.php
- routes/web.php
Added Forgot and Reset Password Features in Login Module
> Forgot and Reset Password Features

- resources/views/components/adminNavigation.blade.php
- resources/views/components/studentNavigation.blade.php
- resources/views/components/superAdminNavigation.blade.php
> FIX: Updated the Extra Navigation Panels

- app/Http/Controllers/Auth/PasswordResetLinkController.php
- resources/css/app.css
- resources/views/auth/forgot-password.blade.php
- resources/views/auth/reset-password.blade.php
This pull request addresses G3A-63 by adding validation in forgot and reset password functionality
> G3A-63 CHORE: Forgot and Reset Password Validation

- resources/views/auth/forgot-password.blade.php
- resources/views/auth/reset-password.blade.php
This pull request addresses G3A-65 by updating forgot password status message text color and size across different screen sizes
> G3A-65 FIX: Forgot Password Status Message Text Color and Size

- resources/views/auth/login.blade.php
This pull request addresses G3A-60 by adding a 3-second auto-fade effect to error messages on the login page and preserving user input when switching between login roles.
> G3A-60 FEAT: Error Fade and Input Persistence on Role Switch

- database/migrations/2025_04_24_052454_create_notifications_table.php
Added new Table for Notification
> CHORE: Added New Table

- app/Http/Controllers/NotificationController.php
- app/Models/Notification.php
added a back endpoints for Send
> CHORE: ADDED a backendpoints for Send

- resources/views/auth/login.blade.php
This pull request addresses 63A-60 email field do not accept spaces
> G3A-60 FIX: Login Email Space Validation

- resources/views/components/adminNavigation.blade.php
- resources/views/components/studentNavigation.blade.php
- resources/views/components/superAdminNavigation.blade.php
New Changes made in the navigation part
> FIX: Navigation Changes

- resources/views/components/adminNavigation.blade.php
- resources/views/components/studentNavigation.blade.php
- resources/views/components/superAdminNavigation.blade.php
Layout for Navigation Bars are remodified. Please check, thank you!
> FIX: Navigation Bars remodified

- composer.lock
PATCH NOTES:
- Composer update Packages installed
> REFACTOR: Composer Package update

- resources/views/super-admin/dashboard.blade.php
Created the user interface for the super admin dashboard
> ADG6-52 FEAT: Create Frontend for Super Admin Dashboard

- app/Http/Controllers/Auth/PasswordResetLinkController.php
- resources/views/auth/reset-password.blade.php
This PR addresses G3A-109 by fixing the reset password for super admin
> G3A-109 FIX: Super Admin Reset Password

- resources/views/auth/login.blade.php
This PR addresses G3A-78 and G3A-79 by adding a real-time input validation to enforce a maximum password length of 50 characters on the sign-in form. It includes visual feedback for users when limits are exceeded and disables the sign-in button until inputs are valid.
> G3A-78 G3A-79 REFACTOR: Adds validation for maximum password length

- app/Http/Controllers/SuperAdminController.php
- app/Models/User.php
- resources/views/super-admin/dashboard.blade.php
- routes/web.php
**ADG6-55 Feat: Initial update on user interface for View Account Details Modal:** 
- Fix some of the user interface for user display in dashboard
- Connect the user database to display the user in dashboard
- Add buttons to sort the user list but still not functioning
- Add validations to the previous and next button
- Add a functioning display page indicator
> ADG6-55 Feat: Initial User Interface for View Account Details Modal

- resources/views/auth/forgot-password.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/reset-password.blade.php
This PR addresses the following:
G3A-82: Fixed the countdown for the "Resend Email" button.
G3A-83: Disabled the "Sign In" button after a single click to prevent multiple submissions.
G3A-84: Disabled the "Send Email" button after one click to avoid duplicate requests.
G3A-87 and G3A-88: Added input validation so that error messages only appear after the user begins typing in the respective fields.
> G3A-82 G3A-83 G3A-84 G3A-87 G3A-88 FIX: Validation

- app/Http/Controllers/SuperAdminController.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
Update the code for fetching the user list from the database to display in the super admin dashboard
> Adg6 59 backend development view account details modal

- composer.lock
Composer updates from 12.10.1 to 12.11.1.
> FEAT: Composer update version

- app/Http/Controllers/SuperAdminController.php
- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
PATCH NOTES:
The following changes has been made:
<b>FIX</b>
- Adjust the Frontend positioning of the Logout Button for Super Admin Navigation Bar
> Adg6 48 fix revise super admin navigation bar frontend

- resources/css/app.css
- resources/views/auth/forgot-password.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/reset-password.blade.php
This PR addresses the following:
- G3A-110 FIX: Prevented the login page from unnecessarily transitioning back to Student mode when an Admin user submits invalid credentials. The selected role now remains consistent after a failed login attempt.
- G3A-77 FIX: Relocated the “Incorrect Email or Password” message to appear directly below the Password field for better clarity and alignment.
- G3A-95 FIX: Disabled the Sign In button when either the Email or Password input is empty to prevent invalid form submission.
- G3A-91 FIX: Implemented smooth transition animations for the login page slideshow to eliminate abrupt changes between slides.
- G3A-108 FIX: Removed the persistent blue highlight on the Email field when using browser autofill for a more polished visual experience.
> Login Page UI Fixes

- resources/views/components/general-components/notification.blade.php
Update the UI for notification in student dashboard only
> REFACTOR NS9-81 : Update Notification UI for student dashboard only

- resources/views/components/general-components/notification.blade.php
Created a function for arrow in notification module
> FEAT NS9-82 : The arrow down in the notification is functioning

- resources/views/super-admin/dashboard.blade.php
The view account details in dashboard can now be viewed
> FEAT ADG6-56: Added Modal

- resources/views/student/components/titleSubmittedDocuments.blade.php
Created the Submitted Document Title Component
> STVC2-78 FEAT: Added Submitted Document TItle Component

- resources/views/student/components/titleSubmittedDocuments.blade.php
- resources/views/student/dashboard.blade.php
Added an inclusion of student Navigation blade in the dashboard.
> Stvc2 57 frontend development student tracker blade view

- app/Http/Controllers/SuperAdminController.php
- app/Http/Controllers/UserController.php
- app/Models/User.php
- database/migrations/2025_05_02_014844_add_role_name_to_users_table.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
- routes/web.php
This pull request enhances the super admin dashboard by adding cache-control headers to prevent access via the browser back button after logout, improving session security. Additionally, it introduces the role_name column to the users table for better role management and display. The SuperAdminController now properly handles sorting by role_name, along with other fields like username and created_at.
> CHORE: Add role_name column to users table and fix role handling

- resources/views/components/adminNavigation.blade.php
- resources/views/components/general-components/notification.blade.php
- resources/views/components/studentNavigation.blade.php
Fixed issue where the notification icon was not displaying
> FIX NS9-89 :  Notification UI Not Displaying on Both Dashboards

- app/Http/Controllers/DocumentController.php
- app/Models/Document.php
- database/migrations/2025_05_03_031958_create_submitted_documents_table.php
This task focuses on establishing the connection between the frontend (UI) and the backend using APIs (Application Programming Interfaces), allowing data to be sent from the form to the server and responses to be received in return.
Key components include:
- API Integration: Use HTTP methods (e.g., POST, GET) to communicate with backend endpoints for submitting form data, uploading files, and storing metadata.
- Data Binding: Capture form inputs (e.g., title, type, related activity, file) and bind them to API requests using JavaScript or a frontend framework (e.g., plain JS).
- Form Submission Handling: Configure the frontend to send a structured request (usually in JSON or multipart/form-data format for file uploads) when the user clicks “Submit.”
- Response Handling: Display …
> FEAT DSM5-30 : Connect UI with backend via API

- resources/views/admin/dashboard.blade.php
- resources/views/admin/documentArchive.blade.php
- resources/views/admin/review.blade.php
- resources/views/components/adminNavBarComponent.blade.php
- resources/views/components/adminSideBarComponent.blade.php
- routes/web.php
<h1> CHANGES </h1>
<h2> FEAT <h2>
- Added Initial Admin Component changes
- Added Document Archive Routes
<h2> FIXES </h2>
- Sidebar content rerouting
- Content Section Adjustments
- Admin Sidebar adjustments
--------------------------------------------------------------------------------------------------------------------------------------------
@extends('base')
@section('content')
@include('components.adminNavBarComponent')
@include('components.adminSidebarComponent')
<div id="main-content" class="transition-all duration-300 ml-[20%]">
//content here
</div>
@endsection
Note: for reference, Look for documentArchive.blade.php
> Stvc2 81 code fixing adjustments to admin document and review module

- resources/views/components/studentSideBarComponent.blade.php
<h1>STUDENT TRACKER AND VERSION CONTROL MODULE</h1>
<h2> FEAT: </h2>
- Development of Student Sidebar Component for Responsiveness
<h1> USAGE </h1>
To use the responsive navigation pane for Sidebar Components, implement this code:
-----------------------------------------------------------------------------------------------------------------------------------------------
@extends('base')
@section('content')
@include('components.adminNavBarComponent')
@include('components.adminSidebarComponent')
<div id="main-content" class="transition-all duration-300 ml-[20%]">
//content here
</div>
@endsection
-----------------------------------------------------------------------------------------------------------------------------------------------
> STVC2-60 FEAT: Added Student Sidebar Component

- app/Http/Controllers/UserController.php
- app/Mail/UserNotificationMail.php
- resources/js/superAdmin.js
- resources/views/components/superAdminNavigation.blade.php
- resources/views/emails/user-notification.blade.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
- resources/views/super-admin/super-admin-component/editUserDeets.blade.php
- routes/web.php
Changes made: 
- Email is automatically sent to the user's gmail when created.
- Editing user's details is now functioning.
- Email is automatically sent to the user's gmail when changes are made.
> ADG6-102 Feat: Sending Email & Edit User Details

- app/Http/Controllers/DocumentController.php
- resources/views/components/studentNavBarComponent.blade.php
- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/submit-documents.blade.php
This task focuses on enabling users to upload document files—specifically PDF and DOC/DOCX formats—through the application interface. The file upload feature is essential for attaching relevant resources, submissions, or references to form entries, tasks, or activities. The submitted info in the file_path column/field is the file path of the uploaded file.
Additional fix: The navigation sidebar is fixed for the student view.
> Dsm5 27 dev implement file upload functionality

- resources/views/components/adminNavBarComponent.blade.php
- resources/views/components/adminSideBarComponent.blade.php
- resources/views/components/superAdminNavigation.blade.php
- resources/views/student/dashboard.blade.php
<h1>SIDEBAR FIXES </h1>
<h2>FIX: </h2>
- Admin Sidebar Fix Issue
- Student Sidebar Fix Issue
> FIX: SIDEBAR FIXES

- resources/views/admin/documentPreview.blade.php
- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/documentArchive.blade.php
- resources/views/student/documentPreview.blade.php
- routes/web.php
> FIX: Document Archive fix

- resources/views/components/adminSideBarComponent.blade.php
> Fix document

- app/Http/Controllers/DocumentController.php
- database/migrations/2025_05_03_031958_create_submitted_documents_table.php
- resources/views/student/submit-documents.blade.php
Event data submission and storage has been implemented. Added 2 new fields to the document submission form: Event Title and Event Description, which, along with the date range, only show up if the document type is an event proposal. Also, event data is stored on the events table.
> FEAT DSM5-58 : Event data submission and storage implemented

- resources/views/student/submit-documents.blade.php
Proper visual cues through toasts for successful and failed document submissions have been implemented based on Figma wireframe.
- When a successful document submission occur, a toast with the message,
> Document Successfully Submitted
> Your document has been submitted successfully. We'll review it shortly and get back to you if anything else is needed.
indicating to the user the document was successfully submitted to the database.
- When a failed document submission occur, a toast with the message,
> Error
> Failed to submit document. Please try again later.
indicating to the user the document was not submitted to the database successfully.
> FEAT DSM5-46 : Added proper visual cues through toasts for successful and failed document submissions

- resources/views/super-admin/dashboard.blade.php
Changes made: 
- Fix the glitch when reloading the dashboard page
- Change the height of the table in the dashboard page
> ADG6-74 Fix: Reloading Page Glitch

- resources/views/auth/reset-password.blade.php
- routes/web.php
This PR addresses G3A-113 by updating the labels on the Reset Password form to ensure clarity and improve user experience.
> G3A-113 Clarify Reset Password Field Labels

- app/Http/Controllers/SuperAdminController.php
- app/Http/Controllers/UserController.php
- app/Mail/UserNotificationMail.php
- app/Models/User.php
- database/migrations/2025_05_06_151050_add_active_column_to_users_table.php
- resources/js/superAdmin.js
- resources/views/emails/user-notification.blade.php
- resources/views/super-admin/super-admin-component/viewAccDeets.blade.php
- routes/web.php
Changes made:
- The deactivation process of an user is now functioning
- Created new column in the user's database (active) that indicates if a user account is activated (1) or deactivated (0)
- need to type in the terminal to migrate the new column in user's table (php artisan migrate)
- Change the design of the email sent to the user for (creation, update details, deactivation)
> ADG6-100 Feat: Deactivate Account

- app/Http/Controllers/Auth/LoginController.php
Update the backend login logic to include a check for the newly added Active column in the user table. Only users with an active status should be allowed to log in.
> G3A-116 CHORE: Implement "Active" Status Check in Login Backend Logic

- app/Http/Controllers/StudentController.php
Student Conroller added for Student Document Archive
> STVC2-84 FEAT:Added  Student Controller

- app/Http/Controllers/StudentTrackerController.php
- resources/views/components/studentSideBarComponent.blade.php
- routes/web.php
STUDENT TRACKER and VERSION CONTROL MODULE
FEAT:
- Added a new Controller that contains to return view  function of Student Tracker Blade View
-  Configured the Route web.php that allows the redirection of this page.
FIX:
- Fix the issue that is making the Tracker button unclickable. It will now redirect to a new page
> Stvc2 85 controllers configure student tracker controller

- resources/js/superAdmin.js
- resources/views/super-admin/dashboard.blade.php
Changes made: 
- Fix the successful modal that pops out when editing user details and deactivating account
- Add button to close the successful modal
> ADG6-81 Fix: Successful Modal

- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/components/titleSubmittedDocuments.blade.php
- resources/views/student/studentTracker.blade.php
TITLE COMPONENT for STUDENT TRACKER AND VERSION CONTROL MODULE
> Stvc2 61 frontend development submitted document title component

- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/components/titleSubmittedDocuments.blade.php
- resources/views/student/components/viewSearch.blade.php
- resources/views/student/studentTracker.blade.php
The official search bar compoent for Student Tracker and Version Control Module
> Stvc2 62 frontend development search bar component

- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/components/titleSubmittedDocuments.blade.php
- resources/views/student/components/viewDocumentTypeDropdown.blade.php
- resources/views/student/components/viewSearch.blade.php
- resources/views/student/studentTracker.blade.php
Document Type Dropdown component
> Stvc2 63 frontend development document type dropdown component

- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/components/titleSubmittedDocuments.blade.php
- resources/views/student/components/viewDocumentTypeDropdown.blade.php
- resources/views/student/components/viewNoRecordsFoundComponent.blade.php
- resources/views/student/components/viewSearch.blade.php
- resources/views/student/studentTracker.blade.php
No records found at the moment Modal
> Stvc2 65 frontend development no records found at the moment display error message component

- app/Http/Controllers/DocumentController.php
- app/Models/Document.php
- database/migrations/2025_05_03_031958_create_submitted_documents_table.php
- resources/views/student/submit-documents.blade.php
- routes/web.php
Fixed and changed a lot of things.
- Keyboard navigable form through the Tab and Enter keys
- Back to Home button working and redirecting to Student Dashboard
- Disabling the submit button until all required fields are filled in
- More importantly, aligning the backend and database with the current ERD of the Document Submission Module.
Please look into each commit and carefully review the changes.
> Dsm5 45 dev validate form inputs and enforce file type constraints

- resources/views/components/studentSideBarComponent.blade.php
- routes/web.php
Sidebar changes as well as the routes
> FIX: Configure Sidebar

- resources/css/app.css
This PR addresses some of the fonts not loading properly due to wrong/invalid directory
> G3A-59 FIX: Update directory of fonts

- app/Http/Controllers/SettingsController.php
- resources/views/student/studentSettings.blade.php
> DBA1-83 FIX: Revised UI

- routes/web.php
Inamers kulang sa bracket walanya
> FIX: Incorporated the bracket

- routes/web.php
> REFACTOR: Rearranged Routes

- resources/views/components/adminSideBarComponent.blade.php
- routes/web.php
Fix the Navigation Sidebar for Admin
> FIX: ADMIN SETTINGS NAVIGATION

- resources/js/super-admin/add-user.js
- resources/js/super-admin/deactivate-user.js
- resources/js/super-admin/edit-user.js
- resources/js/super-admin/main.js
- resources/js/super-admin/modal-base.js
- resources/js/super-admin/success-modal.js
- resources/js/super-admin/user-details.js
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/viewAccDeets.blade.php
Changes made:
- Separate the JavaScript for different blade views
> ADG6-35 Refactor: Organize JavaScript

- resources/js/super-admin/add-user.js
- resources/js/super-admin/success-modal.js
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/deactPage.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
Changes made: Fixed bugs
- Error indication for empty fields during add user creation
- Character limitations on username 
- only accepts email in '@gmail.com' format
- Doesn't accept space-only inputs
- leading/trailing spaces are not allowed in username and email creation
- email case sensitivity validation
- Added confirmation modal for exiting user creation midway
- reset the submission form after exiting the user creation midway
- disabled the add user button in the add user modal until all fields have inputs
> ADG6-104 Fix: Add User Creation Bugs and Validations

- resources/views/components/general-components/notification.blade.php
Update version of Notification UI
> NS9-104 REFACTOR : Update Deisgn for Notification UI

- composer.lock
- package-lock.json
CHORE:
Updates on Laravel version to 12.13.0
Node.js update to 7.27.2
> Stvc2 87 packages npm and composer updates

- resources/views/student/components/viewSubmissionTrackerTitleComponent.blade.php
FEAT:
Added a title component for student document tracker
> STVC2-72 FEAT: Submission Tracker Title Component

- app/Http/Controllers/UserController.php
- resources/js/super-admin/add-user.js
- resources/views/super-admin/super-admin-component/addUser.blade.php
- routes/web.php
Changes made: 
- The existing role in user creation is now hidden and cannot be used to avoid duplication for administrative role
- Proper validation for existing email during user creation
- Added a maximum length inputs in name and email fields
> ADG6-104 Fix: Bug Fixing and Validations

- resources/views/student/components/viewSubmissionTrackerTable.blade.php
FEAT: Generated Displaying Component Table
> STVC2-70 FEAT: Added Student Submit Table Component

- app/Http/Controllers/StudentTrackerController.php
- app/Models/SubmittedDocument.php
- resources/views/student/components/viewSubmissionTrackerTable.blade.php
FIX: Controller Remodification for better navigation
> Stvc2 88 controller fix configure records table

- app/Http/Controllers/StudentTrackerController.php
- app/Models/SubmittedDocument.php
- resources/views/student/components/viewStatusDropdownComponent.blade.php
- resources/views/student/components/viewSubmissionTrackerTable.blade.php
- resources/views/student/studentTracker.blade.php
> Stvc2 90 frontend development fix student tracker blade view

- app/Http/Controllers/StudentTrackerController.php
- app/Models/SubmittedDocument.php
- resources/views/student/components/viewRecordSubmitted.blade.php
- resources/views/student/components/viewStatusDropdownComponent.blade.php
- resources/views/student/components/viewSubmissionTrackerTable.blade.php
- routes/web.php
STUDENT TRACKER AND VERSION CONTROL MODULE
FIX:
- Changes in the Status dropdown by adding a new choice: Pending
- Record navigation added
> Stvc2 78 frontend development fix status dropdown and record navigation

- resources/views/student/components/viewRecordSubmitted.blade.php
STUDENT TRACKER AND VERSION CONTROL MODULE
FEAT
- Added a new blade view after clicking one of the records in the viewStudentTracker Blade View with initial Component Designs (no process happening)
> STVC2-91 FEAT: Added Submission Tracker Blade View

- app/Http/Controllers/StudentTrackerController.php
- app/Models/SubmittedDocument.php
- resources/views/student/components/viewRecordSubmitted.blade.php
- routes/web.php
STUDENT TRACKER AND VERSION CONTROL MODULE
FEAT:
- Added a public function show $id, allowing to display the chosen records to be displayed
- Additionals in the SubmittedDocument.php model
- Component has been called
> Stvc2 77 frontend development submission tracker summary details and chat tracker component

- app/Http/Controllers/NotificationController.php
- app/Models/Notification.php
- resources/views/components/general-components/notification.blade.php
- routes/web.php
New feature for Notification. Users can now 'mark as read' a notification.
> NS9-85 FEAT : new Mark as Read Logic for notification

- app/Http/Controllers/SettingsController.php
- resources/views/student/studentSettings.blade.php
- routes/web.php
Addressed bug tickets DBA1-94 and DBA1-95.
Both issues have been resolved and verified to be working as intended.
> DBA1-86 FIX: BUG DBA1-94 & DBA1-95

- resources/views/components/general-components/notification.blade.php
ADDED:
- Mobile Layout 
- Update Empty State
- Fix confirmation button
> FEAT NS9-103 Mobile Layout and update design

- app/Http/Controllers/AnnouncementController.php
- app/Models/Announcement.php
- database/migrations/2025_05_15_211059_create_announcements_table.php
- resources/views/admin/dashboard.blade.php
- routes/web.php
This pull request introduces the initial database setup required for implementing the announcement creation functionality on the admin side of the system.
> DBA1-66 FEAT: Add Database for announcement creation functionality (admin side)

- resources/js/super-admin/add-user.js
- resources/views/super-admin/super-admin-component/addUser.blade.php
Changes made: 
- Fixed some bugs and validations in add user creation
> ADG6-104 Fix: Bug Fixing

- resources/views/student/components/viewDocumentTypeDropdown.blade.php
- resources/views/student/components/viewRecordSubmitted.blade.php
- resources/views/student/components/viewStatusDropdownComponent.blade.php
- resources/views/student/components/viewSubmissionTrackerTable.blade.php
> Stvc2 147 fullstack development document tracker preview blade view

- resources/views/student/components/viewSubmissionTrackerTable.blade.php
Added changes to the UI of the code, I temporarily use a Traditional CSS and Javascript for this code.
> STVC2-146 REFACTOR: Submission Tracker Table Component Changes

- app/Http/Controllers/AdminDashboardController.php
- app/Http/Controllers/StudentDashboardController.php
- app/Models/Announcement.php
- resources/views/admin/dashboard.blade.php
- resources/views/student/dashboard.blade.php
- routes/web.php
The latest announcement can be now displayed on both the student and admin sides for visibility. Additionally, a toast message has been added to the admin dashboard to confirm successful posting of announcements in real time, and a validation added to the announcement form.
> DBA1 67 Display Latest Announcement Data (Admin & Student Side)

- app/Listeners/submitDocumentListener.php
- app/Models/Notification.php
- database/migrations/2025_05_08_112531_create_notifications_table.php
- resources/views/components/general-components/notification.blade.php
Added:
When a notification is click it navigates to Review Page
> NS9-115 FEAT : Navigate to Review when a Notification is click

- app/Http/Controllers/AdminDashboardController.php
- app/Http/Controllers/StudentDashboardController.php
- resources/views/admin/dashboard.blade.php
- resources/views/student/dashboard.blade.php
Adjustments on the process of displaying list of announcements on the container in both admin and student side.
> DBA-68 refine the display of the announcement list in containers

- app/Http/Controllers/DocumentController.php
- resources/views/student/submit-documents.blade.php
Mainly for bug fixing:
- The submit button in the confirmation popup now disables after clicking it in order to prevent accidental multiple submissions.
- Now, only users with admin roles and their accounts active show on the receiver dropdown list.
- Dropdown list navigation now uses arrow keys instead of the Tab key.
> Dsm5 77 dev add UI polish icons spacing helper texts

- app/Http/Controllers/UserController.php
- resources/js/super-admin/add-user.js
- resources/js/super-admin/edit-user.js
- resources/js/super-admin/user-details.js
- resources/views/super-admin/super-admin-component/editUserDeets.blade.php
- resources/views/super-admin/super-admin-component/viewAccDeets.blade.php
- routes/web.php
Changes made:
- Added validations to add user process
- added validation to edit user account process
> ADG6-104 Fix: Bug Fixing & Adding Validations

- app/Http/Controllers/DocumentReviewController.php
- app/Models/DocumentForward.php
- app/Notifications/DocumentResubmissionRequested.php
- database/migrations/2025_05_08_073944_reviews.php
- database/migrations/2025_05_18_150956_document_forwards.php
- resources/js/admin-review.js
- resources/views/admin/documentReview.blade.php
This pull request introduces several enhancements and updates to the document review system, focusing on new functionalities, improved user notifications, and UI/UX adjustments. Key additions include the ability to forward documents to other admins, improved resubmission handling with notifications, and updates to the admin interface for better usability.
* **Document Forwarding**: Added a new feature to forward documents to other admins, including backend logic (`DocumentForward` model) and a new API endpoint. This includes creating a review record, updating the document's `received_by` field, and notifying the target admin. (`app/Http/Controllers/DocumentReviewController.php` [[1]](diffhunk://#diff-d17a556aa9983df7911bb380a3528ee20c45a7e2b5a6c64890966f04ca292371L347-R446) …
> ADR8-73 : FEAT: Added submit to another admin and request resubmission functionality, FIX: fixed the UI of comment rendering

- resources/views/loading.blade.php
- routes/web.php
INITIAL OVERALL LOADING COMPONENT NOW CAN BE USED FOR TRANSITIONING OF PAGES.
> FEAT: Added Loading Component Asset

- app/Http/Controllers/Auth/LoginController.php
- resources/views/auth/login.blade.php
This PR addresses G3A-132. After the 5th failed attempt, the login form is locked for 5 minutes. A message such as "Too many failed attempts. Please try again after 4:59." appears. Login is also disabled during the lockout period.
> G3A-132 FIX: System Lockout after 5 failed login attempts

- resources/views/admin/documentReview.blade.php
##The table updates now show records from the selected document type
##Changed the header of the review table in accordance to the Figma UI
> ADR8-93 : FIX: The table updates now show records from the selected document type

- resources/js/admin-review.js
- resources/views/admin/documentReview.blade.php
##Success and fail messages for document approval, rejection, resubmission, and send to other admin now appears as a toast.
> ADR8-110 : FIX: Success and fail messages for document approval, rejection, resubmission, and send to other admin now appears as a toast.

- app/Http/Controllers/Auth/LoginController.php
- resources/views/auth/login.blade.php
This PR addresses G3A-145. Once the user interacts with the input fields, the message "You can now try logging in again" disappear automatically.
> G3A-145 FIX: behavior of lockout recovery message when user starts typing

- resources/views/student/components/viewSubmissionTrackerTable.blade.php
- resources/views/student/components/viewSubmissionTrackerTitleComponent.blade.php
STUDENT TRACKER AND VERSION CONTROL MODULE
FIXES:
- Revised the Student Tracker Empty State.
> Stvc2 279 bug fixing fix the empty state design

- app/Http/Controllers/Auth/LoginController.php
- resources/views/auth/login.blade.php
Each login role (Student/Admin) now have its own separate lockout state. Switching to Admin now reset the login form and not display the lockout from the Student side.
> G3A-144 FIX: Lockout for Role

- app/Http/Controllers/SettingsController.php
- database/migrations/0001_01_01_000000_create_users_table.php
- database/migrations/2025_05_21_162338_add_password_changed_at_to_users_table.php
- resources/views/admin/adminSettings.blade.php
- resources/views/student/studentSettings.blade.php
> Settings refinement

- app/Http/Controllers/CommentController.php
- app/Http/Controllers/DocumentReviewController.php
- app/Models/Comment.php
- database/migrations/2025_05_21_175258_comment_attachments.php
- resources/js/admin-review.js
- resources/views/admin/documentReview.blade.php
##FEAT: Added download/printable feature of the document
##FIX: The document review page now is responsive on mobile viewport, The review decision buttons are now disabled when it is already approved/rejected,
> ADR8-74 : FEAT: Added download/printable feature of the document

- app/Http/Controllers/SuperAdminController.php
- database/seeders/DatabaseSeeder.php
- resources/js/super-admin/deactivate-user.js
- resources/js/super-admin/edit-user.js
- resources/js/super-admin/reactivate.js
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/deactPage.blade.php
Changes made: 
- hid the super admin acc in the dashboard
- Fix some bugs in the deactivate process, edit user acc process, and reactivate process.
- Added the profile picture in the dashboard and deactivation page
- Fix the content of the table for dashboard and deactivation page
> Adg6 109 RA-066 super admin account 

- composer.lock
- package-lock.json
Composer Update to 12.15.0
NPM Updates to 22.15.21
> STVC2-246 CHORE: NPM Update 22.15.21 and Laravel Update 12.15.0

- resources/js/super-admin/add-user.js
- resources/views/super-admin/super-admin-component/addUser.blade.php
Changes made: 
- New process of adding user
> ADG6-135 Feat: New Process for Adding User

- app/Events/NewChatMessage.php
- app/Http/Controllers/CommentController.php
- app/Listeners/SendChatNotification.php
- app/Providers/EventServiceProvider.php
- resources/views/components/general-components/notification.blade.php
ADDED:
- When new chat or comment is created the receiver receives a notification
-  Fix design and checkbox functionality and modals
> NS9-114 FEAT : FeedBack Notification

- resources/views/admin/dashboard.blade.php
- resources/views/student/dashboard.blade.php
Fixed an issue where long announcements on the dashboard’s student and admin user side caused layout problems by adding proper text wrapping and overflow handling. Implemented a modal to allow users to view the full content of long announcements.
> DBA1-107 FIX: dashboard and analytics page verify formatting of long announcements overflow handling wrapping

- resources/views/auth/login.blade.php
Once Admin login reaches the lockout condition, its own timer start now at 5:00 (5 minutes), independently of the Student timer and vice versa.
> G3A-138 FIX: Lockout timer independence between roles

- resources/views/loading.blade.php
OVERALL SYSTEM
Loading Component
> Stvc2 245 overall system loading component

- app/Http/Controllers/UserController.php
- app/Models/User.php
- database/migrations/2025_05_22_192150_add_organization_acronym_to_users_table.php
- resources/js/super-admin/add-user.js
- resources/js/super-admin/user-details.js
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
Changes made:
- Functioning new add user 
- added another column in the database for acronym (metadata)
> ADG6-135 Feat: Functioning New Add User Process

- database/migrations/2025_05_23_112219_add_archived_at_to_submitted_documents_table.php
> DAS7-80 - fix table submitted_documents

- resources/views/auth/forgot-password.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/reset-password.blade.php
- resources/views/loading.blade.php
This PR adds a loading component to the login page and integrates it to display during form submission.
> G3A-133 FEAT: added loading components in login page

- app/Listeners/SendChatNotification.php
- resources/views/components/general-components/notification.blade.php
Fix
- Proper routing for Admin
> FIX NS9-93 : Routing for Admin

- public/calendar.css
- resources/views/calendar/index.blade.php
- resources/views/calendar/indexTwo.blade.php
modals confirm and decline added, year scrolldown added, enter key validation added, and some other validations are added
> Coa4 80 UI updates

- app/Http/Controllers/CommentController.php
- app/Http/Controllers/DocumentController.php
- database/seeders/DatabaseSeeder.php
- resources/views/admin/adminSettings.blade.php
- resources/views/components/adminSideBarComponent.blade.php
- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/components/viewRecordSubmitted.blade.php
- resources/views/student/submit-documents.blade.php
- routes/web.php
> FIX: Fix what's wrong

- app/Http/Controllers/StudentDocumentController.php
- database/seeders/DatabaseSeeder.php
- resources/views/student/documentPreview.blade.php
> DAS7-89 - Student document history backend fix

- resources/views/admin/documentReview.blade.php
FIX: text now does not overflow in the dropdown, approval page layout fixed.
REFACTOR: added search reset in the search bar by pressing enter
> ADR8-118 : approval page layout fixed. added search reset in the search bar by pressing enter

- resources/views/super-admin/super-admin-component/addUser.blade.php
Changes made:
- change the acronym in organization to read only
> ADG6-114 Fix: Org_Acronym

- app/Http/Controllers/NotificationController.php
- resources/views/admin/dashboard.blade.php
- resources/views/components/general-components/notification.blade.php
- routes/web.php
Added
- Mark as Read
- Mark as Unread
- Delete 
- Clear All
Fixed
-HTML structure displaying when opening admin or refreshing the page.
Removed
-outdated modal-based confirmation logic
> NS9-97 FEAT New Functions for Notifications

- app/Http/Controllers/Auth/AdminLoginController.php
- app/Http/Controllers/Auth/AdminPasswordResetLinkController.php
- app/Http/Controllers/Auth/StudentLoginController.php
- app/Http/Controllers/Auth/StudentPasswordResetLinkController.php
- app/Http/Controllers/Auth/SuperAdminLoginController.php
- app/Notifications/CustomResetPassword.php
- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/SuperAdminlogin.blade.php
- resources/views/auth/admin-forgot-password.blade.php
- resources/views/auth/admin-password-reset-confirmation.blade.php
- resources/views/auth/admin-reset-password.blade.php
- resources/views/auth/landingPage.blade.php
- resources/views/auth/password-reset-confirmation.blade.php
- resources/views/auth/student-forgot-password.blade.php
- resources/views/auth/student-password-reset-confirmation.blade.php
- resources/views/auth/student-reset-password.blade.php
- resources/views/components/adminNavigation.blade.php
- resources/views/components/adminSideBarComponent.blade.php
- resources/views/components/studentSideBarComponent.blade.php
- resources/views/components/superAdminNavigation.blade.php
- resources/views/student/dashboard.blade.php
- routes/web.php
This PR updates the login page backend --- separating school org and admin roles
> G3A-158 updated school org/admin login page backend

- app/Http/Controllers/NotificationController.php
- app/Listeners/SendChatNotification.php
- app/Listeners/SendDocumentStatusNotification.php
- app/Mail/NotificationAlertMail.php
- resources/views/components/general-components/notification.blade.php
- resources/views/emails/notification-alert.blade.php
Added:
- Email Notification for Students Only
> FEAT NS9-64 : Add Email Notification for Students Only

- app/Http/Controllers/AdminDocumentController.php
- resources/views/admin/archivePage.blade.php
- resources/views/admin/documentHistory.blade.php
- resources/views/student/documentHistory.blade.php
- Added AJAX request for real-time switching of pages
- Hidden pagination when there’s no documents to be shown in the table
- disabled the checkbox whenever there’s no documents in the table
- Tested the forwarding of documents from one admin to another, table filters the documents based on who approved it and who sent it
> DAS7-94 - Fix bus and implemented real-time switching of table page

- app/Http/Controllers/UserController.php
- app/Models/User.php
- package-lock.json
- resources/js/super-admin/add-user.js
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
- routes/web.php
Changes made:
- Fix add new role for student organization (academic and non-academic organization) and administrative staff
- hide existing organization name to the drop down menu
Reminder:
- for student modules - fetch the organization acronym to be displayed at the top right when student org acc is log in (e.g., ELITE)
- for admin modules - fetch the role name to be displayed at the top right when admin acc is log in (e.g., Office of the Campus Director)
> ADG6-46 Fix: Add new role

- resources/js/super-admin/activity-log-modal.js
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/super-admin-component/activityLogModal.blade.php
Created the Activity Log Modal and Page
> ADG6-54 Feat: Activity Log Modal

- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
- routes/web.php
Added:
- Report Icon
- Report Page
> ADDED NS9-150 : Initial Design for Report Page

- app/Http/Controllers/AdminDashboardController.php
- app/Http/Controllers/StudentDashboardController.php
- resources/views/admin/dashboard.blade.php
- resources/views/student/dashboard.blade.php
Implemented a feature that dynamically displays the count of documents based on their current status—pending, under review, and approved. This ensures that both student organizations and administrators can view real-time updates on the status of submitted documents directly from their respective dashboards.
> DBA1-90 FEAT: Data Presentation of Documents Status Update Counts.

- app/Http/Controllers/ProblemReportController.php
- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/landingPage.blade.php
This update enhances the file upload functionality in the Problem Report form to support not only images but also document files (PDF, DOCX, DOC).
> G3A-151 FIX: Allow PDF, DOCX, and DOC File Uploads in Problem Report Form

- resources/css/app.css
- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/admin-forgot-password.blade.php
- resources/views/auth/admin-reset-password.blade.php
- resources/views/auth/landingPage.blade.php
- resources/views/auth/student-forgot-password.blade.php
- resources/views/auth/student-reset-password.blade.php
- resources/views/student/submit-documents.blade.php
This PR updates some of the modal design to make it more consistent across all roles
> G3A-162 FIX: Made modal design on login pages consistent

- app/Http/Controllers/CommentController.php
- composer.lock
- database/seeders/DatabaseSeeder.php
- package-lock.json
- resources/js/student-comments.js
- resources/views/student/components/viewRecordSubmitted.blade.php
- resources/views/student/components/viewSubmissionTrackerTitleComponent.blade.php
Fix Changes in the Comment Section in Student Tracker
> STVC2-234 FIX: Incomplete Fix Chatbox Feature

- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
ADDED:
-UI UPDATE
-ATTACHEMENT FETCHING
> REFACTOR NS9-153 : REPORT PAGE UPDATED UI

- app/Http/Controllers/SuperAdminController.php
- resources/js/super-admin/activity-log-modal.js
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/super-admin-component/activityLogModal.blade.php
- routes/web.php
Initial UI for Activity Log Page
> ADG6-41 Feat: Activity Log Page UI

- app/Http/Controllers/SettingsController.php
- app/Http/Controllers/SuperAdminController.php
- app/LogsActivity.php
- app/Models/ActivityLog.php
- database/migrations/2025_06_01_015456_create_activity_logs_table.php
- resources/views/student/studentSettings.blade.php
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/dashboard.blade.php
- routes/web.php
Fix: Settings Bug 
Feat: Implement backend logic for Activity Log
[Activity Log Manual.pdf](https://github.com/user-attachments/files/20535853/Activity.Log.Manual.pdf)
> Fix: Settings Bug

- resources/js/app.js
- resources/js/super-admin/admin-dropdown.js
- resources/views/base.blade.php
- resources/views/components/superAdminNavigation.blade.php
- routes/web.php
- vite.config.js
Changes made: 
- Added the super admin drop down menu for settings and log out button in the nav bar
> ADG6-145 Feat: Settings and Logout Button

- app/Http/Controllers/DocumentController.php
- app/Models/Event.php
- database/migrations/2025_04_25_034149_create_events_table.php
- resources/views/student/submit-documents.blade.php
- Completely removed the event start date and event end date from the module
> REFACTOR DSM5-87 : Removed event start and end date from the module

- resources/js/super-admin/add-user.js
- resources/js/super-admin/auto-logout.js
- resources/js/super-admin/edit-user.js
- resources/js/super-admin/user-details.js
- resources/views/base.blade.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/deactPage.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
- resources/views/super-admin/super-admin-component/editUserDeets.blade.php
- vite.config.js
Changes made: 
- Removed the name input for admin role
- Disabled the role field when editing user
- include the organization acronym in view acc details and in editing
- fix the functionality of pagination button for dashboard and deactivated page
- Added an automatic log out and modal confirmation after 15 minutes of inactivity
> ADG6-145 Fix: Remove Name Input for Admin Role

- app/Http/Controllers/AnnouncementController.php
- resources/views/admin/dashboard.blade.php
- resources/views/student/dashboard.blade.php
Handles the formatting of long unbroken words.
> DBA1-112 FIX: Formatting of Long Announcements

- app/Http/Controllers/Auth/AdminLoginController.php
- app/Http/Controllers/Auth/AdminPasswordResetLinkController.php
- app/Http/Controllers/Auth/StudentLoginController.php
- app/Http/Controllers/Auth/StudentPasswordResetLinkController.php
- app/Http/Controllers/ProblemReportController.php
- app/LogsActivity.php
- app/Models/ProblemReport.php
- database/migrations/2025_06_03_112920_rename_screenshot_path_to_file_path_in_problem_reports_table.php
- package-lock.json
- resources/views/super-admin/super-admin-component/reports.blade.php
This PR addresses G3A-176 by implementing backend support for logging user activities such as login, password reset, and problem report submission into the database.
> G3A-176 FEAT: Add backend logic for saving activity logs of login module

- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/landingPage.blade.php
This update introduces a live character counter inside the description textarea field of the problem report modal.
> G3A-181 FIX:  Add live character counter for description

- app/Http/Controllers/SuperAdminController.php
- resources/js/super-admin/reactivate.js
- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/deactPage.blade.php
- resources/views/super-admin/super-admin-component/activityLogModal.blade.php
- routes/web.php
Changes made: 
- Activity log modal is now functioning
- Activity log page UI updated
- UI for dashboard and deactivated page updated to match size of 100%
> ADG6-58 Feat: Activitiy Log Modal

- app/Events/NewAnnouncement.php
- app/Http/Controllers/AnnouncementController.php
- app/Listeners/NewAnnouncementListener.php
- app/Mail/AnnouncementMail.php
- app/Providers/EventServiceProvider.php
- resources/views/emails/announcement.blade.php
Added:
- Notification Announcement
- Email Announcement
- Logs
-
> FEAT NS9-169 : Announcement Notification

- resources/views/components/general-components/notification.blade.php
- resources/views/emails/announcement.blade.php
- resources/views/emails/notification-alert.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
FIXED:
-Report Page Attachment can now be viewed
-Notification Layout(for long title and messages)
-Email Notification Layout(for long title and messages)
> NS9-170 FIX : Report Page & Notification

- resources/views/auth/landingPage.blade.php
- routes/web.php
This PR added a guest role in landing page with redirection to the new page for guest
> G3A-189 FEAT: Added guest role

- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/admin-forgot-password.blade.php
- resources/views/auth/admin-password-reset-confirmation.blade.php
- resources/views/auth/admin-reset-password.blade.php
- resources/views/auth/student-forgot-password.blade.php
- resources/views/auth/student-password-reset-confirmation.blade.php
- resources/views/auth/student-reset-password.blade.php
This PR made pages like login, forgot, landing pages responsive across different sizes.
> G3A-188 FIX: Made login, forgot, landing pages responsive

- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/super-admin-component/addUser.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
Changes made:
- fix the search button for both report and activity log page to be able to search in the entire table container
- fixt the filter button on both report and activity log page to be able to filter by date (newest, oldest, this day, this month, this year)
- Added a custom option for filtering dates on both activity log and report page)
> ADG6-145 Fix: Search and Filter Button

- routes/web.php
> G3A 179 FIX: Login Route

- app/Http/Controllers/DocumentController.php
- resources/views/student/submit-documents.blade.php
Changes:
- Control tag field now uses the value on the organization acronym field of the sender from the users table
- Dropdowns, subject and summary fields now have proper rounded borders which match the updated Figma
- Changed the submit button on the confirmation popup from color green to color red
> Dsm5 93 dev update to new submission form

- resources/views/student/components/viewRecordSubmitted.blade.php
- resources/views/student/components/viewStatusDropdownComponent.blade.php
- resources/views/student/components/viewSubmissionTrackerTitleComponent.blade.php
- resources/views/student/studentTracker.blade.php
FIXES ON STUDENT TRACKER MODULE
> STVC2 FIX: Status Fetching Changes

- resources/js/admin-review.js
- resources/views/admin/documentReview.blade.php
FIX : fixed the color coding of the flow of document transaction, implemented direct viewing of image attachment in comment, initial placeholder for Event Proposal document type info, return status overflow fix.
> Adr8 126 correct color coding and clarity of flow for document status

- package-lock.json
- package.json
- vite.config.js
> Deployment Changes

- app/Http/Controllers/UserController.php
- resources/js/super-admin/add-user.js
- resources/js/super-admin/edit-user.js
- resources/views/super-admin/super-admin-component/editUserDeets.blade.php
Changes made: 
- Fix the edit user for admin role
- allow additional email input for @yahoo.com and @iskolarngbayan.pup.edu.ph
> ADG6-145 Fix: Edit User Details

- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/SuperAdminlogin.blade.php
- resources/views/auth/admin-forgot-password.blade.php
- resources/views/auth/student-forgot-password.blade.php
> G3A-186 FIX: Email Format validation

- resources/js/super-admin/add-user.js
- resources/views/components/superAdminNavigation.blade.php
Changes made:
- fix the super admin settings route 
- can now input dash (-) in the add new role field
> ADG6-145 Fix: Super Admin Settings Route

- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/SuperAdminlogin.blade.php
- resources/views/auth/admin-forgot-password.blade.php
- resources/views/auth/admin-reset-password.blade.php
- resources/views/auth/student-forgot-password.blade.php
- resources/views/auth/student-reset-password.blade.php
- resources/views/loading.blade.php
This PR addresses the loading component not covering the whole page in mobile view and the loading component persisting on browser back navigation
> G3A-194 FIX: Loading component fix behavior

- app/Http/Controllers/AnnouncementController.php
- app/Http/Controllers/SuperAdminController.php
- resources/views/admin/dashboard.blade.php
- resources/views/super-admin/dashboard.blade.php
- routes/web.php
This PR add a functionality for the super admin user. Now the user can post, edit, archive, restore, and delete announcements.
> Dba1 118 super admin announcement functionality

- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
- resources/views/auth/admin-reset-password.blade.php
- resources/views/auth/landingPage.blade.php
- resources/views/auth/student-reset-password.blade.php
If no input is entered: No prompt should appear when exiting.
> G3A-180 FIX: validation on exiting report a problem form

- app/Http/Controllers/EventController.php
- public/calendar.css
- resources/views/calendar/index.blade.php
- resources/views/calendar/indexTwo.blade.php
bug fix for calendar tag time not being shown properly
> Coa4 139 check event details labels

- app/Http/Controllers/Auth/AdminPasswordResetLinkController.php
- app/Http/Controllers/Auth/StudentPasswordResetLinkController.php
- app/Models/User.php
This PR enables the user to use recovery email for sending of forgot password email link
> G3A-192 FIX: Send reset link to recovery email if used

- resources/views/auth/Adminlogin.blade.php
- resources/views/auth/Studentlogin.blade.php
This PR fixes the lockout attempts/message on submission results to browser history stack.
> G3A-178 FIX: login page browser back behavior

- app/Http/Controllers/AdminDocumentController.php
- app/Http/Controllers/StudentDocumentController.php
- resources/views/admin/documentPreview.blade.php
FIXED MODIFIED TABLE NAME BY OTHER GROUP
> DAS7-109 - CONNECTION FIX

- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/dashboard.blade.php
Changes made:
- fix the routing for super admin settings and reports
> ADG6-145 Fix: Fix Routes

- package-lock.json
- package.json
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
- vite.config.js
Changes made:
- Activity Log can now generate and download a PDF Report
- Report Page can now generate and download a PDF Report
> ADG6-145 Feat: Generate PDF

- app/Http/Controllers/AdminDashboardController.php
- app/Http/Controllers/AnnouncementController.php
- resources/views/admin/dashboard.blade.php
Authenticating users by validating the admin users to edit only the announcements posted by them. While the super admin can edit any announcements.
> DBA1-131 FEAT: User Authentication on Editing Announcements

- resources/views/student/components/viewRecordSubmitted.blade.php
Data Fetching for Student Tracker changes
> FIX: Data Fetching Student Tracker

- app/Http/Controllers/SuperAdminController.php
- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/deactPage.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
- routes/web.php
Changes made:
- Added the recovery email in the view account details
- allow editing of recovery email in both user's settings and super admin's account editing
- Various validation for recovery email input
- added profile picture in the super admin nav bar
- fix generate report for both report page and activity log page pdf view
- allow generate report base on filtering settings
- fix pagination functionality for dashboard, activity log page, report page, deactivated page
-
> ADG6-145 Fix: Generate Report Functionality

- resources/views/super-admin/super-admin-component/reports.blade.php
Fixed: 
Close Button for Modal
> FIXED NS9-189 : Close button for Modal

- .github/workflows/deploy.yml
- README.md
> Automation deployment branch

- README.md
> CHORE: ReadME changes

- database/seeders/DatabaseSeeder.php
- public/calendar.css
- resources/views/calendar/index.blade.php
- resources/views/calendar/indexTwo.blade.php
> Coa4 140 check the add event details overlap

- resources/js/super-admin/success-modal.js
- resources/views/super-admin/dashboard.blade.php
> ADG6-145 Fix: Succesful Modal

- app/Http/Controllers/DocumentController.php
- app/Http/Controllers/GuestSubmitDocumentController.php
- resources/views/guest/guestSubmissionSuccess.blade.php
- routes/web.php
Changes:
- Implemented proper session handling for guest document submission
> FIX : Implemented proper session handling for guest document submission

- app/Http/Controllers/EventController.php
- public/calendar.css
- resources/views/calendar/index.blade.php
- resources/views/calendar/indexTwo.blade.php
mobile responsiveness and added modals.
> Coa4 141 UI mobile

- resources/views/components/general-components/notification.blade.php
Added:
-Users can now select all  or deselect all notifications
> FEAT NS9-185 : Select All & Deselect All

- app/Http/Controllers/Auth/SuperAdminPasswordResetLinkController.php
- resources/views/auth/SuperAdminlogin.blade.php
- resources/views/auth/superadmin-forgot-password.blade.php
- resources/views/auth/superadmin-password-reset-confirmation.blade.php
- resources/views/auth/superadmin-reset-password.blade.php
- routes/web.php
> G3A-199 FEAT: Super Admin Forgot Password

- app/Http/Controllers/AdminDocumentController.php
- app/Http/Controllers/DocumentExportController.php
- app/Http/Controllers/StudentDocumentController.php
- resources/views/admin/archivePage.blade.php
- resources/views/admin/documentHistory.blade.php
- resources/views/student/archivePage.blade.php
- resources/views/student/documentHistory.blade.php
changed ADMIN ‘DOCUMENT HISTORY’ TO DOCUMENT REPOSITORY
UPDATED STATUS FIELD IN TABLE → ADMIN USER_ROLE
FIX DROPDOWN, MADE IT DYNAMIC FOR ORGANIZATION AND TYPES. FOR STUDENT AND ADMIN.
> DAS7-115 - module changes

- app/Http/Controllers/SuperAdminController.php
- resources/js/super-admin/add-user.js
- resources/views/components/superAdminNavigation.blade.php
- resources/views/super-admin/actLogPage.blade.php
- resources/views/super-admin/dashboard.blade.php
- resources/views/super-admin/deactPage.blade.php
- resources/views/super-admin/super-admin-component/activityLogModal.blade.php
- resources/views/super-admin/super-admin-component/reports.blade.php
- routes/web.php
Changes made: 
- Responsiveness of SuperAdminNavigation
- Responsiveness of dashboard, deact page, reports page, act log page
- Real-time fetching for activity log page
-
> ADG6-145 Fix: Responsiveness and Real time Update

- public/calendar.css
- resources/views/calendar/index.blade.php
- resources/views/calendar/indexTwo.blade.php
> Coa4 142 UI follow up mobile

- app/Http/Controllers/DocumentController.php
- app/Mail/GuestSubmissionConfirmation.php
- resources/views/emails/guestOtp.blade.php
- resources/views/emails/guestSubmissionConfirmation.blade.php
- resources/views/guest/guestSubmissionForm.blade.php
- resources/views/student/submit-documents.blade.php
- Updated the academic year dropdown list for student organizations and guests down to previous 5 and 2 years respectively
- Implemented confirmation email for guest document submission
- Fixed the logo for guest emails by replacing .svg with .png
- Fixed the proposed date & time field by limiting the user to not allow picking past dates
> Dsm5 78 dev guest email confirmation and other fixes

- resources/views/super-admin/super-admin-component/reports.blade.php
This pull request enhances the `reports.blade.php` file by introducing a document viewer modal for previewing and downloading attachments. The changes include the addition of a modal UI, integration with PDF.js for PDF rendering, and support for previewing image files. The modal also provides functionality for switching between preview and download views.
> FIXED NS9-198 : Report View Attachment

- app/Http/Controllers/AdminDocumentController.php
- app/Http/Controllers/StudentDocumentController.php
- resources/views/admin/archivePage.blade.php
- resources/views/admin/documentHistory.blade.php
- resources/views/admin/documentPreview.blade.php
- resources/views/student/archivePage.blade.php
- resources/views/student/documentHistory.blade.php
> DAS7-121 - FIX BUGS

- resources/views/components/studentSideBarComponent.blade.php
- resources/views/student/components/viewSubmissionTrackerTable.blade.php
BUG FIXES:
- Adjustments to Color Assignment for Status Tracking
> STVC2-303 FIX: Bug Fix Status Tracker Column

- resources/views/emails/announcement.blade.php
- resources/views/emails/notification-alert.blade.php
- resources/views/emails/user-notification.blade.php
- resources/views/super-admin/actLogPage.blade.php
Changes made: 
- Fix the logo when emailing the user
- fix the generate report in the activity log page to download only one day worth of report
> ADG6-198 Fix: Email Logo and Act Log PDF Report

- app/Http/Controllers/AdminDashboardController.php
- app/Http/Controllers/StudentDashboardController.php
- resources/views/admin/dashboard.blade.php
- resources/views/student/dashboard.blade.php
- resources/views/super-admin/dashboard.blade.php
- routes/web.php
The dashboard can now update real time, no need to refresh the website to fetch all the previous information under the dashboard functionality. Also adjusted the curser pointer on buttons
> DBA1-146 FEAT:  Real Time Update Dashboard

- app/Http/Controllers/GuestSubmitDocumentController.php
- resources/views/emails/guestOtp.blade.php
- resources/views/emails/guestSubmissionConfirmation.blade.php
- resources/views/guest/guestLogin.blade.php
- resources/views/guest/guestSubmissionForm.blade.php
- resources/views/guest/guestSubmissionSuccess.blade.php
- resources/views/guest/guestVerifyLogin.blade.php
- resources/views/student/submit-documents.blade.php
- routes/web.php
Changes:
- Changed the word "Guest" to "Class Representative"
- Fixed the academic year field dropdown list to the proper order, also changed the word "Midyear" to "Mid Year"
- Fixed the E-skolarian logo not loading in the guest emails
- Added the "Back to Login" button to all guest blade views
- Added alerts when trying to go out of the submission forms after filling in input fields
> Dsm5 120 dev bug fixing

- resources/views/admin/dashboard.blade.php
Announcement submission form now resets and reactivates button properly
> fix: announcement submission form

- public/calendar.css
> COA4-156-Modal BG fix

- app/Http/Controllers/Auth/AdminPasswordResetLinkController.php
- app/Http/Controllers/Auth/StudentLoginController.php
- app/Http/Controllers/DocumentReviewController.php
- app/Http/Controllers/SuperAdminController.php
- resources/views/super-admin/actLogPage.blade.php
Changes made: 
- fix the fetching of activity logs name for admin 
- fix the generated pdf downloaded to prevent the table from being put at the second page
-
> ADG6-198 Fix: Activity Logs

- resources/views/admin/documentReview.blade.php
FIX: fixed filter for "petition and concern"
> FIX: fixed filter for "petition and concern"

- resources/views/guest/guestSubmissionForm.blade.php
- resources/views/student/submit-documents.blade.php
Change:
- Deleted faulty JS code for pop-up alerts in student and guest document submission modules
> FIX : Removed the faulty JS alert code for student and guest document submission module

- resources/views/student/components/viewRecordSubmitted.blade.php
- resources/views/student/components/viewSubmissionTrackerTitleComponent.blade.php
Remodifications in UI when Returning the Document
> STVC2 FIX: UI Remodifications

- app/Http/Controllers/DocumentReviewController.php
- app/Models/Review.php
- database/migrations/2025_05_03_031958_create_submitted_documents_table.php
- database/migrations/2025_05_08_073944_reviews.php
- database/migrations/2025_07_03_083157_forward_document.php
- resources/js/admin-review.js
- resources/views/admin/documentReview.blade.php
- routes/web.php
REFACTOR: implemented AGAIN the forward functionality
> REFACTOR: implemented AGAIN the forward functionality

- app/Http/Controllers/DocumentController.php
- resources/views/guest/guestSubmissionForm.blade.php
- resources/views/student/submit-documents.blade.php
Change:
- Added a modal popup that shows control tag to the user after submitting documents
> FEAT DSM5 : Added modal popup that shows control tag to user after document submission
